### ISSUE TITLE
Move the JuliaPerf

### ISSUE THREAD

**Issue by vchuravy** [mchristianl/IntelITT.jl#1]
@mchristianl I would love to make the Julia VTune integration a bit smoother,
would you be interested in moving this code to JuliaPerf so that we can maintain it as a community?

**Comment by vchuravy** [comment]
Note that I just created https://github.com/JuliaPerf/ITT.jl since I realized we need to actually use the dylib that comes with VTune.

**Comment by mchristianl** [comment]
Yes, perfect. Thank you for working on this!

Can I transfer rights of this repository or would it be more helpful to remove it completely? (If ITT.jl is working, this repository is obsolete anyways)

**Comment by vchuravy** [comment]
If you are okay with it, I would take the name `IntelITT.jl` and you could archive this repository?

**Comment by mchristianl** [comment]
Yes, I am okay with that. I will archive this repository on Wednesday.
